# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: curl -LJO https://downloads-sast.mend.io/sast-cli/linux/mendsastcli && chmod +x mendsastcli
  displayName: 'Downloading Mend SAST Tool'

- script: ./mendsastcli --dir ./ --name=$(Build.Repository.Name)$(Build.SourceBranchName) --app AZ$(System.TeamProject)
  displayName: 'Run Mend SAST'
  env:
    SAST_ORGANIZATION: $(SAST_ORGANIZATION)
    SASTCLI_TOKEN: $(SASTCLI_TOKEN)
    SAST_SERVER: https://saas.mend.io/sast/